port:6222
http:6280
jetstream {
    store_dir=C:\\tmp\\jetstream\\6222
}
server_name=server3
client_advertise: localhost:6222
cluster {
  name: cluster
  listen: 127.0.0.1:6223
  routes: [
    nats-route://127.0.0.1:4223
    nats-route://127.0.0.1:5223
  ]
}
