port:5222
http:5280
jetstream {
	store_dir=C:\\tmp\\jetstream\\5222
}
server_name=server2
client_advertise: localhost:5222
cluster {
  name: cluster
  listen: 127.0.0.1:5223
  routes: [
    nats-route://127.0.0.1:4223
    nats-route://127.0.0.1:6223
  ]
}
